const Order = require('../models/order.model');
const Cart = require('../models/cart.model');
const Product = require('../models/product.model');
const asyncHandler = require('../utils/asyncHandler');
const AppError = require('../utils/AppError');

// Must match the exact session ID used in the cart controller
const TEST_SESSION_ID = "test-session-123";

// GET /api/orders — Retrieve all orders
exports.getAllOrders = asyncHandler(async (req, res, next) => {
  const orders = await Order.find();
  
  res.status(200).json({
    status: 'success',
    message: 'Orders retrieved successfully',
    data: orders
  });
});

// GET /api/orders/:id — Retrieve a single order by ID
exports.getOrderById = asyncHandler(async (req, res, next) => {
  const order = await Order.findById(req.params.id);
  if (!order) {
    throw new AppError('Order not found', 404);
  }

  res.status(200).json({
    status: 'success',
    message: 'Order retrieved successfully',
    data: order
  });
});

// POST /api/orders — Checkout: turn the cart into a new order
exports.createOrderFromCart = asyncHandler(async (req, res, next) => {
  const { street, city, country } = req.body;

  if (!street || !city || !country) {
    throw new AppError('Please provide a complete shipping address (street, city, country).', 400);
  }

  // Step 1: Get the current cart using the sessionId string
  const cart = await Cart.findOne({ user: TEST_SESSION_ID });
  if (!cart || cart.items.length === 0) {
    throw new AppError('Your cart is empty. Add items before placing an order.', 400);
  }

  const orderItems = [];
  let calculatedTotalPrice = 0;

  // Step 2 & 3: Validate stock and compute price server-side from Product database
  for (const item of cart.items) {
    const product = await Product.findById(item.product);
    if (!product) {
      throw new AppError(`Product with ID ${item.product} no longer exists.`, 404);
    }

    if (product.stock < item.quantity) {
      throw new AppError(
        `Not enough stock for "${product.name}". Available stock: ${product.stock}, requested: ${item.quantity}.`,
        400
      );
    }

    // Server-side calculation from database price (Not accepting cart prices!)
    const itemTotalPrice = product.price * item.quantity;
    calculatedTotalPrice += itemTotalPrice;

    // Step 4: Snapshot details to preserve names and prices
    orderItems.push({
      product: product._id,
      name: product.name,
      price: product.price,
      quantity: item.quantity
    });
  }

  // Create order (orderNumber auto-generated by the order pre-validate hook!)
  const order = await Order.create({
    items: orderItems,
    totalPrice: calculatedTotalPrice,
    shippingAddress: { street, city, country }
  });

  // Step 5: Reduce the stock of every product
  for (const item of cart.items) {
    const product = await Product.findById(item.product);
    product.stock -= item.quantity;
    await product.save(); // Triggers product pre-save hooks (like inStock recalculation)
  }

  // Step 6: Empty the cart
  cart.items = [];
  await cart.save(); // Triggers cart pre-save hook (resets totalPrice to 0)

  // Step 7: Return the new order
  res.status(201).json({
    status: 'success',
    message: 'Order completed successfully!',
    data: order
  });
});

// PATCH /api/orders/:id/status — Update the status of an order
exports.updateOrderStatus = asyncHandler(async (req, res, next) => {
  const { status } = req.body;
  if (!status) {
    throw new AppError('Status is required to update order progress.', 400);
  }

  const order = await Order.findById(req.params.id);
  if (!order) {
    throw new AppError('Order not found', 404);
  }

  order.status = status;
  await order.save();

  res.status(200).json({
    status: 'success',
    message: 'Order status updated successfully',
    data: order
  });
});